<?php 
	include('../config.php');
	if(isset($_COOKIE['TestCookieSecond'])){
			unset($_COOKIE['TestCookieSecond']);
		setcookie("TestCookieSecond",$dool,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['TestCookieSecond'])){
		true;
	}
	if(isset($_COOKIE['TestCookie'])){
		unset($_COOKIE['TestCookie']);
		setcookie("TestCookie",$doo,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['TestCookie'])){
		true;
	}
	if(isset($_COOKIE['business-content'])){
		unset($_COOKIE['business-content']);
		setcookie("business-content",12,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['business-content'])){
		true;
	}
	if(isset($_COOKIE['user-content'])){
			unset($_COOKIE['user-content']);
		setcookie("user-content",11,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['user-content'])){
		true;
	}
	if(isset($_COOKIE['push'])){

		unset($_COOKIE['push']);
		setcookie("push","",time()-3600,'/');
	}
	elseif(!isset($_COOKIE['push'])){
		true;
	}
	if(isset($_COOKIE['user-content-state'])){
		unset($_COOKIE['user-content-state']);
		setcookie('user-content-state',11,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['user-content-state'])){
		true;
	}
	if(isset($_COOKIE['user-content-state-data'])){
		unset($_COOKIE['user-content-state-data']);
		setcookie('user-content-state-data',11,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['user-content-state-data'])){
		true;
	}
	if(isset($_COOKIE['business-content-state'])){
	unset($_COOKIE['business-content-state']);
		setcookie('business-content-state',12,time()-3600,'/');	
	}
	elseif(!isset($_COOKIE['business-content-state'])){
		true;
	}
	if(isset($_COOKIE['business-content-state-data'])){
		unset($_COOKIE['business-content-state-data']);
		setcookie('business-content-state-data',12,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['business-content-state-data'])){
		true;
	}
	if(isset($_COOKIE['user-content-state-push'])){
		unset($_COOKIE['user-content-state-push']);
		setcookie('user-content-state-push',11,time()-3600,'/');
	}
	elseif(!isset($_COOKIE['user-content-state-push'])){
		true;
	}
	header( 'Location: /', true, 307 );
?>